config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :bands do
    resources :bookings
  end

  resources :venues do
    resources :bookings
  end

  resources :bookings
  get "bookings/:id/booking_data", to: "bookings#booking_data"
  get "bands/:id/next", to: "bands#next"
  post "/bookings/json", to: "bookings#create_json"

  resources :users, only: [:new, :create]

  get "login" => "sessions#new", as: "login"
  post "login" => "sessions#create"
  get "logout" => "sessions#destroy", as: "logout"


  root "static#welcome"

  get '/auth/google_oauth2/callback', to: 'sessions#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/band.rb
class Band < ApplicationRecord
  has_many :shows, class_name: :Booking

  validates :name, presence: true
  validates :rate, numericality: { only_integer: true}

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :band
  belongs_to :venue

  def self.next_show
    order("showtime").where("showtime > ?", Time.current).limit(1)
  end

  def self.sort_by_showtime
    order("showtime")
  end

  def next_button
    band = self.band
    show = Booking.order("showtime").where("showtime > ? AND band_id = ?", self.showtime, band.id).first
    if show
      show
    else
      Booking.order("showtime").where("band_id = ?", band.id).first
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one :venue

  def self.find_or_create_by_omniauth(auth_hash)
    if user = User.find_by(username: auth_hash["uid"])
      user
    else
      User.create(username: auth_hash["uid"], password: SecureRandom.hex)
    end
  end
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :bookings
  has_many :bands, through: :bookings
  belongs_to :user

  validates :name, presence: true

  # def venue_owner?
  #   @venue.user_id == current_user.id
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def require_login
    return head(:forbidden) unless session.include? :user_id
  end

  def current_user
    @user ||= User.find_by(id: session[:user_id])
  end

  def venue_owner?
    venue = Venue.find_by(id: params[:booking][:venue_id])
    current_user.venue_id == venue.id
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_login

  def index
    @bands = Band.all
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_path(@band)
    else
      render :new
    end
  end

  def show
    @band = Band.find(params[:id])
    @show = @band.shows.next_show.first
  end

  def next
    current_show = Booking.find(params[:id])
    # @band = Band.find(params[:id])
  
    @next_show = current_show.next_button
    render json: @next_show
  end

  private
  def band_params
    params.require(:band).permit(:name, :description, :rate)
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :require_login
  before_action :set_booking, only: [:edit, :update, :destroy]

  def index
    if params[:venue_id]
      @venue = Venue.find_by(id: params[:venue_id])
      if @venue.nil?
        flash[:message] = "Venue not found"
        redirect_to venues_path
      else
        @bookings = @venue.bookings
      end
    elsif params[:band_id]
      @band = Band.find_by(id: params[:band_id])
      if @band.nil?
        flash[:message] = "Band not found"
        redirect_to bands_path
      else
        @bookings = @band.shows
      end
    else
      @bookings = Booking.all
    end
    respond_to do |format|
      format.json {render json: @bookings}
      format.html {render :index}
    end
  end

  def show
    if params[:venue_id]
      @venue = Venue.find_by(id: params[:venue_id])
      @booking = @venue.bookings.find_by(id: params[:id])
      if @booking.nil?
        flash[:message] = "Booking not found"
        redirect_to venue_bookings_path
      end
    elsif params[:band_id]
      @band = Band.find_by(id: params[:band_id])
      @booking = @band.shows.find_by(id: params[:id])
      if @booking.nil?
        flash[:message]  = "Booking not found"
        redirect_to band_bookings_path
      end
    else
      set_booking
    end
  end

  def new
    # if venue, venue_owner?
    @booking = Booking.new(band_id: params[:band_id], venue_id: params[:venue_id])
  end

  def create
    if venue_owner?
      @booking = Booking.new(booking_params)
      if @booking.save
        redirect_to booking_path(@booking)
      else
        render :new
      end
    else
      flash[:message] = "You must be registered as the venue owner to perform this action"
      redirect_to new_booking_path
    end
  end

  def create_json
    if venue_owner?
      @booking = Booking.new(booking_params)
      if @booking.save
        render json: @booking
      else
        render :new
      end
    else
      flash[:message] = "You can only create bookings at your venue"
      redirect_to new_booking_path
    end
  end

  def edit

  end

  def update
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  def destroy
    if venue_owner?
      @booking.delete
      flash[:message] = "Booking successfully deleted."
      redirect_to bookings_path
    else
      flash[:message] = "You can only cancel bookings at your venue"
      redirect_to booking_path(@booking)
    end
  end

  private
  def booking_params
    params.require(:booking).permit(:band_id, :venue_id, :showtime)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if auth_hash = request.env["omniauth.auth"]
      user = User.find_or_create_by_omniauth(auth_hash)
      session[:user_id] = user.id
      redirect_to bookings_path
    else
      @user = User.find_by(username: params[:user][:username])
      if @user && @user.authenticate(params[:user][:password])
       session[:user_id] = @user.id
       redirect_to bookings_path
      else
       render :new
      end
    end
  end

  def destroy
    session.delete :user_id if session[:user_id]
    redirect_to root_path
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def welcome
    if current_user
      redirect_to bookings_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to bookings_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :venue_owner, :venue_id)
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :require_login
  # before_action :venue_owner?
  # skip_before_action :venue_owner?, only: [:index, :show]

  def index
    @venues = Venue.all
  end

  def new
    @venue = Venue.new
  end

  def create
    @venue = Venue.new(venue_params)
    if @venue.save
      redirect_to venue_path(@venue)
    else
      render :new
    end
  end

  def edit
    @venue = Venue.find(params[:id])
  end

  def update
    @venue.update(venue_params)
    redirect_to venue_path(@venue)
  end

  def show
    @venue = Venue.find(params[:id])
    # @next_show = @venue.bookings.next_show.first
    @booking = @venue.bookings.build
  end

  private
  def venue_params
    params.require(:venue).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def format_showtime(t)
    t.strftime("%B %-d, %Y at %-I:%M%p")
  end

  def show_count_message(shows)
    count = shows.count
    if count == 0
      "No scheduled shows"
    else
      pluralize(count, 'show') + " scheduled"
    end
  end

end

app/views/bands/_form.html.erb
<% if @band.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@band.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @band.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @band do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>

  <%= f.label :description %><br>
  <%= f.text_area :description %><br>

  <%= f.label :rate %><br>
  <%= f.text_field :rate %><br><br>

  <%= f.submit %>
<% end %>

app/views/bands/edit.html.erb
<h1>Edit Band</h1>

<%= render partial: 'form' %>

app/views/bands/index.html.erb
<h1>All Bands</h1>
<div class="band-list col s4">

    <% @bands.each do |band| %>
      <h5> <%= link_to band.name, band_path(band) %> </h5>
      <a href="/bands/<%=band.id%>/bookings.json" class="js-all">> <%= show_count_message(band.shows) %></a>
      <br>
    <% end %>

</div>
<div class="shows-list right col s8">

</div>
<br><br>

<h5><%= link_to "Add a Band", new_band_path %></h5>

app/views/bands/new.html.erb
<h1>New Band Form</h1>

<%= render partial: 'form' %>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<p><%= @band.description %></p>

<p><strong>Rate: </strong>$<%= @band.rate %> </p> <br>

<h3>Next Show:</h3>


  <% if @show.nil? %>
    <p>There are currently no shows scheduled for this band.</p>
  <% else %>
    <div class="display-show">
      <h4><%=@show.venue.name%></h4>
      <p> <%= format_showtime(@show.showtime) %> </p>
      <p><strong>About the Venue:</strong> <%=@show.venue.description%></p>
      <div class="divider"></div>
    </div>
    <br>
    <button class="js-next" data-band-id="<%= @band.id %>" data-show-id="<%=@show.id%>">See next</button>
  <% end %>




<br>
<h4><%= link_to "See all upcoming shows", band_bookings_path(@band) %></h4>

<h4><%= link_to "Book this band", new_band_booking_path(@band) %></h4>

app/views/bookings/_form.html.erb
<%= form_for @booking do |f| %>
  <% if params[:band_id] %>
    <%= f.hidden_field :band_id %>
  <% else %>
    <%= f.label :band %>
    <%= f.collection_select :band_id, Band.all, :id, :name %><br>
  <% end %>

  <% if params[:venue_id] %>
    <%= f.hidden_field :venue_id %>
  <% else %>
    <%= f.label :venue %>
    <%= f.collection_select :venue_id, Venue.all, :id, :name %><br>
  <% end %>

  <%= f.label :showtime %>
  <%= f.datetime_select :showtime %><br>
  
  <%= f.submit %>
<% end %>

app/views/bookings/edit.html.erb
<h1>Edit Booking Form</h1>

<%= render 'form' %>

app/views/bookings/index.html.erb
<h1>All Shows</h1>

<% @bookings.each do |show| %>
  <p><%= link_to show.band.name, band_path(show.band) %> at <%= link_to show.venue.name, venue_path(show.venue) %> </p>
  <p><%= link_to format_showtime(show.showtime), booking_path(show) %></p><br>
  <div class="divider">

  </div>
<% end %>

app/views/bookings/new.html.erb
<h1>New Booking Form</h1>

<%= render 'form' %>

app/views/bookings/show.html.erb
<h1>Band: <%= @booking.band.name %></h1>

<h2>Venue: <%= @booking.venue.name %></h2>

<h3>Showtime: <%= @booking.showtime.strftime("%B %-d, %Y at %-I:%M%p") %> </h3>

<p><%= link_to "Edit", edit_booking_path(@booking) %></p>
<br>
<p><%= link_to "Cancel Show", booking_path(@booking), method: 'delete' %></p>

app/views/layouts/_header.html.erb
<nav class="navbar brown">
  <ul>
    <li><%= link_to "All Shows", bookings_path %></li>
    <li><%= link_to "All Bands", bands_path %></li>
    <li><%= link_to "All Venues", venues_path %></li>
    <li><%= link_to "Book a Band", new_booking_path %></li>
    <% if session[:user_id] %>
      <li class="right"><%= link_to "Log Out", logout_path %></li>
    <% end %>
  </ul>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookAShowRailsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body >
    <header>
      <%= render 'layouts/header' %>
    </header>
    <div class="container">

      <div id="flash-msg">
        <% if flash[:message] %>
          <p style = "color:red;"> <%= flash[:message] %></p>
        <% end %>
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br>

  <%= f.label :password %>
  <%= f.password_field :password %><br>

  <%= f.label :venue_id, "Select a venue if you are an owner" %>
  <%= f.collection_select :venue_id, Venue.all, :id, :name, include_blank: true, html: {class: "js-create datetime"} %><br>

  <%= f.submit "Create User" %>

<%end%>

app/views/venues/_form.html.erb
<% if @venue.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@venue.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @venue.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @venue do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>

  <%= f.label :description %><br>
  <%= f.text_area :description %><br>

  <%= f.submit %>
<% end %>

app/views/venues/edit.html.erb
<h1>Edit Venue Form</h1>

<%= render partial: 'form' %>

app/views/venues/index.html.erb
<h1>Venue Index</h1>

<ul>
  <% @venues.each do |venue| %>
    <li> <%= link_to venue.name, venue_path(venue) %> - <%= show_count_message(venue.bookings) %></li><br>
  <% end %>
</ul>

<br>
<p><%= link_to "Add a Venue", new_venue_path %></p>

app/views/venues/new.html.erb
<h1>New Venue Form</h1>

<%= render partial: 'form' %>

app/views/venues/show.html.erb
<h1> <%= @venue.name %> </h1>

<p><%= @venue.description %></p>

<h3>Scheduled shows:</h3>
<% @venue.bookings.each do |show| %>
  <% if show.id %>
    <h4><%= link_to show.band.name, band_path(show.band) %> </h4>
    <p> <%= format_showtime(show.showtime) %> </p>
    <p> <%= link_to "Link to Show", booking_path(show) %></p><br>
  <% end %>
<% end %>

<div class="added-booking">
  <h4 id="band-name"></h4>
  <p id="showtime"></p>
  <p id="link"></p>
</div>

<h4>Book a band at this venue</h4>

<%= form_for @booking, html: {class: "js-create datetime"} do |f|  %>
  <% if params[:band_id] %>
    <%= f.hidden_field :band_id %>
  <% else %>
    <%= f.label :band %>
    <%= f.collection_select :band_id, Band.all, :id, :name %><br>
  <% end %>

  <% if params[:venue_id] %>
    <%= f.hidden_field :venue_id %>
  <% else %>
    <%= f.label :venue %>
    <%= f.collection_select :venue_id, Venue.all, :id, :name %><br>
  <% end %>

  <%= f.label :showtime %>
  <%= f.datetime_select :showtime %><br>

  <%= f.submit 'Add Show'%>
<% end %>
<br>